namespace Waddle.Core.Symbols {
    public enum TokenType {
        Identifier,
        Number,
        String,
        Function,
        LParen,
        RParen,
        LBrace,
        RBrace,
        Plus,
        Arrow,
        Minus,
        Times,
        If,
        Colon,
        Semicolon,
        Comma,
        Type,
        Print,
        Push,
        Length,
        Return,
        Equals,
        FString,
        For,
        Var,
        Match,
        And,
        Or,
        LessThan,
        GreaterThan,
        LessEquals,
        GreaterEquals,

        // ...
        Multiply,
        Divide,
        Equal,
        Dot,
        Comment,
        Unknown
    }
}