namespace Waddle.Core.Symbols {
    public enum TokenType {
        Identifier,
        Number,
        String,
        Function,
        LParen,
        RParen,
        LBrace,
        RBrace,
        Plus,
        Arrow,
        Minus,
        Times,
        If,
        Colon,
        Semicolon,
        Type,
        Print,
        Return,
        Equals,
        String,
        FString,
        For,
        Let,
        Var,
        Match,
        Push,
        Length,
        And,
        Or,
        LessThan,
        GreaterThan,
        LessEquals,
        GreaterEquals,
        

        // ...
    }
}